# COMPONENT
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-native-test
  description: A spring native test application
spec:
  type: service
  lifecycle: experimental
  owner: guests
  providesApis:
    - spring-test-api
---
# API
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: spring-test-api
  description: does nothing
spec:
  type: openapi
  lifecycle: production
  owner: guests
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/dab6854d4d599aafb0eb36e6c7ae1fe0c37509b7/APIs/spotify.com/2021.4.2/openapi.yaml