apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: eAo=
metadata:
  name: dockerconfigjson-github-com
  labels:
    {{- include "springnativetest.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson