replicaCount: 1
image:
  repository: ghcr.io/jp-silva/spring-native-test
  pullPolicy: IfNotPresent
  tag: v0.0.26
imagePullSecrets:
  - name: dockerconfigjson-github-com
nameOverride: springnativetest
fullnameOverride: springnativetest
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: NodePort
  port: 80
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
