apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-native-test
  description: A spring native test application
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: springnativetest
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: public-websites